### ISSUE TITLE
please make a video how to use it 

### ISSUE THREAD

**Issue by imranwebdeveloper123** [41337/stripe-checker#10]
hi there, please make a video on this topic how to use  it, can I get social media link

**Comment by 41337** [comment]
hy @imranwebdeveloper123  maybe one day I will do something like this, if I do my channel is here: https://www.youtube.com/channel/UCOVGvhkbosaz3ktSVksbr8A/featured

**Comment by imranwebdeveloper123** [comment]
> hy @imranwebdeveloper123 maybe one day I will do something like this, if I do my channel is here: https://www.youtube.com/channel/UCOVGvhkbosaz3ktSVksbr8A/featured

Bro please make a video i want to check cc

**Comment by 41337** [comment]
> > hy @imranwebdeveloper123 maybe one day I will do something like this, if I do my channel is here: https://www.youtube.com/channel/UCOVGvhkbosaz3ktSVksbr8A/featured
> 
> Bro please make a video i want to check cc
Okay

**Comment by imranwebdeveloper123** [comment]
> > > hy @imranwebdeveloper123 maybe one day I will do something like this, if I do my channel is here: https://www.youtube.com/channel/UCOVGvhkbosaz3ktSVksbr8A/featured
> > 
> > 
> > Bro please make a video i want to check cc
> 
> Okay

thank u bro waiting for ur video
