### ISSUE TITLE
SCHECKER ERROR COMMAND

### ISSUE THREAD

**Issue by adamhalimi** [41337/stripe-checker#13]
i followed all the steps but when I type on the cmd "schecker list nameofthefile.txt" it prints me an error message, the message is that cmd doesn't know "schecker" as a command or a batch file, please help me rn!!

**Comment by 41337** [comment]
yes because you must pass the path to the executable, for example:

> Windows
```ps1
.\schecker list nameofthefile.txt
```
> Unix
```sh
./schecker list nameofthefile.txt
```

**Comment by shady741482** [comment]
its dosnt worke

**Comment by L3m0n-Cao** [comment]
are you in the same directory as the "schecker" file is in?
