### ISSUE TITLE
stripe status 400

### ISSUE THREAD

**Issue by rezaeination** [41337/stripe-checker#14]
[ERROR] Request error from Stripe (status 400): {"status":400,"message":"No valid payment method types for this Payment Intent. Please ensure that you have activated payment methods compatible with your chosen currency in your dashboard (https://dashboard.stripe.com/settings/payment_methods) or specify payment_method

Payment method is enabled on my account, nothing wrong from my side from what i see. what's causing this?

**Comment by 41337** [comment]
account is flagged / bumped into a card with no online payment method activated

**Comment by 41337** [comment]
> account is flagged / bumped into a card with no online payment method activated

@rezaeination

**Comment by rezaeination** [comment]
> 

i had messed up something in the config file, that's what caused my issue. but i have another problem, 
I'm getting cards that get marked as live, but with the error: {"status":400,"message":"This PaymentIntent (pi_3LZPkmCbYOjhtZwo0OU6Gt4T) does not have a successful charge to refund.","request_id":"req_vSEeY8TOXM7tQN","type":"invalid_request_error"}

however, with some other card types, no errors occur, but it marks the payment as fraudulent and locks the account, just wondering if for the first issue, what is happening exactly, and for my second issue, if an aged stripe account would solve it, or if this is going to happen regardless.

**Comment by 41337** [comment]
@rezaeination  this is due to cards that do not have online purchase enabled
when they don't have it activated they get a popup asking for payment confirmation

**Comment by daothanhluan9292** [comment]
> [ERROR] Request error from Stripe (status 400): {"status":400,"message":"No valid payment method types for this Payment Intent. Please ensure that you have activated payment methods compatible with your chosen currency in your dashboard (https://dashboard.stripe.com/settings/payment_methods) or specify payment_method
> 
> Payment method is enabled on my account, nothing wrong from my side from what i see. what's causing this?

I had a similar problem. Have you solved it yet? Please tell me how to solve it
