### ISSUE TITLE
schecker once 5555555555555555|05|2025|555   -bash: 05: command not found -bash: 2025: command not found -bash: 555: command not found -bash: schecker: command not found

### ISSUE THREAD

**Issue by SosiskaSardelka** [41337/stripe-checker#16]
schecker once 5555555555555555|05|2025|555  
-bash: 05: command not found
-bash: 2025: command not found
-bash: 555: command not found
-bash: schecker: command not found

**Comment by 41337** [comment]
bro you forgot `schecker once "5555555555555555|05|2025|555"`
