### ISSUE TITLE
Tengo un problema

### ISSUE THREAD

**Issue by Jasony60** [41337/stripe-checker#19]
El checker me indica error 400, parameter-invalid-integer

**Comment by 41337** [comment]
@Jasony60 
si esto sucede por el monto, entonces active su cuenta porque está en modo de prueba

**Comment by Jasony60** [comment]
Mi cuenta no esta en modo prueba me decia primero que tengo que poner un numero entero, pero luego puse un dolar y como quiera me decia parametro invalido
![Uploading IMG-20220901-WA0199.jpeg…]()

**Comment by 41337** [comment]
use 0100

**Comment by Jasony60** [comment]
Sin punto ni nada asi mismo 0100

**Comment by Jasony60** [comment]
Como ago para que la clave no se queme al instante

**Comment by Jasony60** [comment]
Lo hice y funciono pero stripe dio alerta de alto riesgo
