### ISSUE TITLE
Error de bloqueo

### ISSUE THREAD

**Issue by Jasony60** [41337/stripe-checker#20]
Me bloquearon la clave sk_live dijo pago fraude y me bloquio , no se siempre me hace este error parece que ago algo malo @

**Comment by 41337** [comment]
si, sucede es un precio a pagar

**Comment by Jasony60** [comment]
Osea siempre me hace mismo pero si no le pongo precio me da error quisiera que funcione normal y no me bloque la sklive

**Comment by Jasony60** [comment]
Si le pongo me cierra la cuenta
