### ISSUE TITLE
Error when checking ccs

### ISSUE THREAD

**Issue by skiiity** [41337/stripe-checker#21]
![image](https://user-images.githubusercontent.com/104527870/188320664-6d596578-a568-423a-8d0b-393c1e795b6d.png)
how can i fix:

[ERROR] Request error from Stripe (status 400): {"status":400,"message":"No valid payment method types for this Payment Intent. Please ensure that you have activated payment methods compatible with your chosen currency in your dashboard (https://dashboard.stripe.com/settings/payment_methods) or specify payment_method_types","param":"payment_method_types","request_id":"req_4PPzSSQMcl8DdA","type":"invalid_request_error"}

**Comment by 41337** [comment]
Hy @skiiity 
Check if your account is active (in production mode) or if your account is in the country where the currency you want to use is located.

for example: my account is from brazil, so i can only accept brl, if i put usd i get an error. this can also happen with invalid amount like 001 instead of 010

**Comment by skiiity** [comment]
what does amount mean btw?

**Comment by 41337** [comment]
@skiiity 
amount of your configuration
```yaml
stripePublishKey: "..."
stripePrivateKey: "..."
amount: "...." # <-- Amount
currency: "..."
```

**Comment by skiiity** [comment]
Hey, my account is in gbp and i put gbp but am still getting the same error.

my config:

stripePublishKey: "pk_live_51LeKefLMuojS82e9olNTztJxIUZB8PkZKtfRr7mwcn8zhEVSI7pGDJWbQ8coNRjfeFtkWe6VSwYRaYcdlfQ1ATX700mcKT7nZw"
stripePrivateKey: "sk_live..."
ammount: "001"
currency: "gbp"

I hid my private key of course.

**Comment by 41337** [comment]
@skiiity  Use 010 in "ammount" and send feedback

**Comment by skiiity** [comment]
> @skiiity Use 010 in "ammount" and send feedback

I tried but still same error. Even with new stripe account

**Comment by 41337** [comment]
@skiiity clone and try again.

**Comment by skiiity** [comment]
> @skiiity clone and try again.

Tried that just now. Same error for some reason.

**Comment by 41337** [comment]
@skiiity  I just updated the project just now, try again now.

**Comment by skiiity** [comment]
> @skiiity I just updated the project just now, try again now.

![image](https://user-images.githubusercontent.com/104527870/189499127-c3178a76-9110-4c6d-ab78-f38b372b5caa.png)
same error

**Comment by 41337** [comment]
I believe that the cards are not coming through this path

**Comment by 41337** [comment]
do a cat in the direction of the file with the cards and see if it is returning something

**Comment by 41337** [comment]
Also send me the format you are using in the example cards: 5555555555555555|55|55|555
