### ISSUE TITLE
Request error from Stripe

### ISSUE THREAD

**Issue by p1nngu** [41337/stripe-checker#22]
└─# ./schecker  --config-path config.yaml l list
[info] ammount: 100
[info] currency: ron
[info] publish key: pk_live_51Li5H5...
[info] private key: sk_live_51Li5H5...
[ERROR] Request error from Stripe (status 400): {"status":400,"message":"No valid payment method types for this Payment Intent. Please ensure that you have activated payment methods compatible with your chosen currency in your dashboard (https://dashboard.stripe.com/settings/payment_methods) or specify payment_method_types","param":"payment_method_types","request_id":"req_EBu55nozniwC73","type":"invalid_request_error"}
[error] {"status":400,"message":"No valid payment method types for this Payment Intent. Please ensure that you have activated payment methods compatible with your chosen currency in your dashboard (https://dashboard.stripe.com/settings/payment_methods) or specify payment_method_types","param":"payment_method_types","request_id":"req_EBu55nozniwC73","type":"invalid_request_error"}

**Comment by 41337** [comment]
check #21

**Comment by rxkhim** [comment]
bash: 55: command not found
bash: 55: command not found
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/41337/stripe-checker/src.CardSplit({0x7fff9efcb7d3, 0x81c031}, {0x816e86, 0x1})
    /home/runner/stripe-checker/stripe-checker/src/funcs.go:25 +0x1a6
main.main.func1(0xc0001e69a0)
    /home/runner/stripe-checker/stripe-checker/cli.go:41 +0x65
github.com/urfave/cli.HandleAction({0x7776a0, 0x83fa98}, 0x4)
    /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:526 +0x50
github.com/urfave/cli.Command.Run({{0x81795c, 0x4}, {0x0, 0x0}, {0xc0001be860, 0x2, 0x2}, {0x824626, 0x11}, {0x0, ...}, ...}, ...)
    /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.9/command.go:173 +0x652
github.com/urfave/cli.(*App).Run(0xc000292380, {0xc000198060, 0x3, 0x3})
    /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:277 +0x705
main.main()
    /home/runner/stripe-checker/stripe-checker/cli.go:93 +0x3b4
bash: 555: command not found

**Comment by rxkhim** [comment]
https://imgur.com/a/AjDvaTg
