### ISSUE TITLE
Dudas

### ISSUE THREAD

**Issue by Jasony60** [41337/stripe-checker#23]
Tengo una duda y si no quisiera ponerle ningun monto a la cc solo quisiera verificarla podria hacerlo, poniendo 0000 en el cargo

**Comment by 41337** [comment]
noup

**Comment by Jasony60** [comment]
Entonces hermano digame, como hacerle que no se me muera la sklive cuando aga el cargo

**Comment by 41337** [comment]
@Jasony60 see the code, a refund is made so our card doesn't die

**Comment by Jasony60** [comment]
I mean, that's clear to me, but stripe immediately charges me, kills my api and blocks my account

**Comment by 41337** [comment]
yes stripe bans accounts with a lot of wrong payment flow that are not verified

**Comment by Jasony60** [comment]
So how can it be done because if I don't check because they blocked me I won't be able to use the checker, and thank you very much brother for clearing up some doubts and helping me

**Comment by 41337** [comment]
@Jasony60  so man, thanks for helping! Idk how u can do to not get banned :/

**Comment by Jasony60** [comment]
the solution is in an api called setup-payment that is used to verify the cc and save them for future payments, and it does not make any type of charge, it only verifies and saves but I don't know how to implement it
