### ISSUE TITLE
help

### ISSUE THREAD

**Issue by heubsjs** [41337/stripe-checker#9]
![image](https://user-images.githubusercontent.com/111277710/184614165-8594eb5a-191c-4607-a8e4-8c70871fac6e.png)

**Comment by 41337** [comment]
hy @heubsjs 
change the line to: github.com/41337/stripe-checker

**Comment by 41337** [comment]
could you show the go.mod ?

**Comment by 41337** [comment]
@heubsjs 
after changing the line everything goes back to normal, thanks for the report it was a silly mistake because I had changed my nickname
![image](https://user-images.githubusercontent.com/88632118/184671938-0c26b95d-a49f-4d27-babf-f8a8d5a548a5.png)
